global uictrls;
uictrls = {};
uictrls.fig             = figure('Position',[100,300,450,250],...
                        'NumberTitle','off','DoubleBuffer','on',...
                        'BackingStore','on','Renderer','Painters',...
                        'Name','Learning Rule Fit','MenuBar','none');
    
clf(uictrls.fig);    


global quitsim;
quitsim=0;


uictrls.tau_pre_edit      = uicontrol('Style', 'edit',...
                            'String', '0.03',...
                            'Position', [280 150 100 20]);
uictrls.tau_pre_label       = uicontrol('style','text',...
                            'Position',[400 150 100 20],'String','taupre');       

uictrls.tau_post_edit      = uicontrol('Style', 'edit',...
                            'String', '0.03',...
                            'Position', [280 120 100 20]);
uictrls.tau_post_label       = uicontrol('style','text',...
                            'Position',[400 150 100 20],'String','taupost');       

uictrls.amp_post_edit      = uicontrol('Style', 'edit',...
                            'String', '0.001',...
                            'Position', [280 180 100 20]);
uictrls.amp_post_label       = uicontrol('style','text',...
                            'Position',[400 180 100 20],'String','amppost');       

uictrls.amp_pre_edit      = uicontrol('Style', 'edit',...
                            'String', '0.001',...
                            'Position', [280 210 100 20]);
uictrls.amp_pre_label       = uicontrol('style','text',...
                            'Position',[400 210 100 20],'String','amppre');       

uictrls.amp_non_edit      = uicontrol('Style', 'edit',...
                            'String', '0.001',...
                            'Position', [280 240 100 20]);
uictrls.amp_non_label     = uicontrol('style','text',...
                            'Position',[400 240 100 20],'String','ampnon');       

uictrls.offset_edit      = uicontrol('Style', 'edit',...
                            'String', '0.001',...
                            'Position', [280 90 100 20]);
uictrls.offset_label     = uicontrol('style','text',...
                            'Position',[400 90 100 20],'String','offset');       
% uictrls.tau_syn_ratio      = uicontrol('Style', 'slider',...
%                             'Min',0,'Max',1,'Value',GC_model.tau_s_ratio,...
%                             'Position', [280 208 100 20]);                    
% uictrls.tau_syn_ratio_label= uicontrol('style','edit',...
%                             'Position',[400 210 30 20],'String',num2str(0));       

uictrls.plotFits          = uicontrol('Style','pushbutton',...
                            'Position',[50 75 150 20],'String','Plot Fits','Value',0,...
                            'Callback',{'plotPlasticityFits', gc_rates, ...
                            convolved_rates, voltage_changes, delays, times, plotHandle, ...
                            learningRulePlot});

uictrls.fitAmpsGlobal     = uicontrol('Style','checkbox',...
                            'Position',[40 100 150 20],'Value',0);

uictrls.fitAmpsGlobal_label     = uicontrol('style','text',...
                            'Position',[60 100 150 20],'String','fit amps global');       


uictrls.fitAmpSep     = uicontrol('Style','checkbox',...
                            'Position',[40 140 150 20],'Value',0);

uictrls.fitAmpSep_label     = uicontrol('style','text',...
                            'Position',[60 140 150 20],'String','fit amps separately');       


