uictrls = {};
uictrls.fig             = figure('Position',[10,400,450,250],...
                        'NumberTitle','off','DoubleBuffer','on',...
                        'BackingStore','on','Renderer','OpenGL',...
                        'Name','Granule Matcher','MenuBar','none');
    
clf(uictrls.fig);    


uictrls.quitbutton          = uicontrol('Style','pushbutton',...
                            'Position',[280 10 150 20],'String','Quit','Value',0,'Callback',{'quitbutton'});
global quitsim;
quitsim=0;

uictrls.GC_to_use_label     = uicontrol('style','text',...
                            'Position',[280 115 30 20],'String','GC: ','FontSize',14);  
uictrls.GC_to_use           = uicontrol('Style','popup',...
                            'Position',[315 115 120 20],'String',gctypes,'Value',1);
                    
uictrls.runs_to_avg_label   = uicontrol('style','text',...
                            'Position',[280 80 100 20],'String','Runs to avg: ','FontSize',14);  
uictrls.runs_to_avg =       uicontrol('style','edit',...
                            'Position',[400 80 30 20],'String',num2str(10));    

uictrls.spikes              = uicontrol('Style','checkbox',...
                            'Position',[50 10 150 20],'String','Spiking On','Value',0);

synapse_sliders = {};
synapse_numbers = {};
for i=1:3

    synapse_sliders{i}      = uicontrol('Style', 'slider',...
                            'Position', [130 88+35*(i-1) 100 40],'Min',0,'Max',10,'Value',0.5);
                        
    synapse_numbers{i}      = uicontrol('Style','popup',...
                            'Position',[20 90+35*(i-1) 100 40],'String',{'no input', mftypes{:}},'Value',1);

end
uictrls.synapse_sliders = synapse_sliders;
uictrls.synapse_numbers = synapse_numbers;


uictrls.tau_syn_slider      = uicontrol('Style', 'slider',...
                            'Min',0,'Max',5,'Value',0.2,...
                            'Position', [280 148 100 20]);
uictrls.tau_syn_label       = uicontrol('style','edit',...
                            'Position',[400 150 30 20],'String',num2str(0));       

uictrls.tau_mem_slider      = uicontrol('Style', 'slider',...
                            'Min',0,'Max',30,'Value',8.7,...
                            'Position', [280 178 100 20]);                    
uictrls.tau_mem_label       = uicontrol('style','edit',...
                            'Position',[400 180 30 20],'String',num2str(0));       

uictrls.fitweights          = uicontrol('Style','pushbutton',...
                            'Position',[50 75 150 20],'String','Fit Weights','Value',0,...
                            'Callback',{'gui_fitweights',uictrls,rspstore,real_cells,plotwin}); %passing figure bad
                        
uictrls.resetweights        = uicontrol('Style','pushbutton',...
                            'Position',[50 45 150 20],'String','Reset Weights','Value',0,...
                            'Callback',{'gui_resetweights',uictrls});