clear all;
close all;
gc_names = {'CD_ipsp',...
            'CDpause_GCs',...
            'med',...
            'PCA',...
            'PCA_CDpause_GCs',...
            'PCA_late',...
            'PCA_med',...
            'PCA_med_late'};

granule_plotter;
        